name: Docker Image CI

on:
  push:
    branches:
      - main
  create:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        tag="${GITHUB_REF##*/}"
        upstream_tag="$tag"
        if [ "$tag" = "main" ]
        then
          upstream_tag="v19"
        fi
        image_name="ghcr.io/cubyte-oss/ceph:${tag}-cubyte"
        podman build --build-arg UPSTREAM_TAG="$upstream_tag" -t "$image_name" .
        podman push "$image_name"

