name: Docker Image CI

on:
  push:
    branches:
      - main
  create:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Login to GitHub Container Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        repo="ghcr.io/cubyte-oss/ceph"
        tmp_image="$repo:latest"
        podman build -t "$tmp_image" .
        tag="v$(podman run --rm -it "$tmp_image" ceph -v 2>&1 | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')-cubyte"
        image="$repo:$tag"
        podman tag "$tmp_image" "$image"
        podman push "$image"

