name: Docker Image CI

on:
  create:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --build-arg UPSTREAM_TAG="${GITHUB_REF##*/}" --tag "pschichtel/ceph:${GITHUB_REF##*/}"
        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        docker push "pschichtel/ceph:${GITHUB_REF##*/}"

